apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickstart-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickstart-docker
  template:
    metadata:
      labels:
        app: quickstart-docker
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
